# Generated by Django 5.1.1 on 2024-09-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_file', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlsfiles',
            name='file',
        ),
        migrations.AddField(
            model_name='urlsfiles',
            name='urls',
            field=models.TextField(default='default_url'),
        ),
    ]
