# Generated by Django 5.1.1 on 2024-09-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_file', '0002_remove_urlsfiles_file_urlsfiles_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlsfiles',
            name='content',
            field=models.TextField(default='No data'),
        ),
    ]
